<?php if (comments_open()) : ?>
	<?php do_action('comment_form_before'); ?>
	<div class="respond" id="respond">
		<h3 id="reply-title"><?php comment_form_title(__('Leave a Reply'), __('Leave a Reply to %s')); ?> <small><?php cancel_comment_reply_link(__('Cancel reply')); ?></small></h3>
		<?php if (get_option( 'comment_registration' ) && !is_user_logged_in()) : ?>
			<p class="must-log-in"><?php echo $data['must_log_in']; ?></p>
			<?php do_action('comment_form_must_log_in_after'); ?>
		<?php else : ?>
			<form action="<?php echo site_url( '/wp-comments-post.php' ); ?>" method="post" id="commentform">
				<?php do_action( 'comment_form_top' ); ?>
				<?php if (is_user_logged_in()) : ?>
					<p class="logged-in-as">
						<?php echo apply_filters('comment_form_logged_in', $data['logged_in_as'], $commenter, $user_identity); ?>
					</p>
					<?php do_action( 'comment_form_logged_in_after', $commenter, $user_identity ); ?>
				<?php else : ?>
					<p class="comment-notes"><?php echo __('Your email address will not be published.') . ($data['req'] ? sprintf(' ' . __('Required fields are marked %s'), '<span class="required">*</span>') : '' ) ?></p>
					<?php do_action('comment_form_before_fields'); ?>
					<p class="comment-form-author">
						<label for="author"><?php echo __('Name') ?></label>
						<?php if ($data['req']) : ?><span class="required">*</span><?php endif; ?>
					    <input id="author" name="author" type="text" value="<?php esc_attr($data['commenter']['comment_author']) ?>" size="30"<?php echo $data['aria_req'] ?> />
					</p>
					<p class="comment-form-email">
						<label for="email"><?php echo __('Email') ?></label>
						<?php if ($data['req']) : ?><span class="required">*</span><?php endif; ?>
					    <input id="email" name="email" type="text" value="<?php esc_attr($data['commenter']['comment_author_email']) ?>" size="30"<?php echo $data['aria_req'] ?> />
					</p>
					<p class="comment-form-url">
						<label for="url"><?php echo __('Website') ?></label>
						<input id="url" name="url" type="text" value="<?php esc_attr($data['commenter']['comment_author_url']) ?>" size="30"<?php echo $data['aria_req'] ?> />
					</p>
					<?php do_action('comment_form_after_fields'); ?>
				<?php endif; ?>
				<p class="comment-form-comment">
					<label for="comment"><?php echo __('Comment') ?></label>
					<?php if ($data['req']) : ?><span class="required">*</span><?php endif; ?>
					<textarea id="comment" name="comment" cols="72" rows="8" aria-required="true"></textarea>
				</p>
				<p class="form-allowed-tags">
					<?php echo sprintf( __( 'You may use these <abbr title="HyperText Markup Language">HTML</abbr> tags and attributes: %s' ), ' <code>' . allowed_tags() . '</code>') ?>
				</p>
				<p class="form-submit">
					<input name="submit" type="submit" id="submit" value="<?php echo esc_attr(__('Post Comment')); ?>" />
					<?php comment_id_fields($data['post_id']); ?>
				</p>
				<?php do_action('comment_form', $data['post_id']); ?>
			</form>
		<?php endif; ?>
	</div><!-- #respond -->
	<?php do_action('comment_form_after'); ?>
<?php else : ?>
	<?php do_action('comment_form_comments_closed'); ?>
<?php endif; ?>