<?php

/**
 * The template for displaying Comments.
 *
 * The area of the page that contains both current comments
 * and the comment form. The actual display of comments is
 * handled by a callback to terrific_comment() which is
 * located in the functions.php file.
 *
 * @package WordPress
 * @subpackage Terrific
 * @since Terrific 1.0
 */

?>
<?php if (post_password_required()) : ?>
 <p class="nopassword"><?php _e( 'This post is password protected. Enter the password to view any comments.', 'terrific' ); ?></p>
<?php
	/* Stop the rest of comments.php from being processed,
	 * but don't kill the script entirely -- we still have
	 * to fully load the template.
	 */
	return;
endif;
?>
<?php if (have_comments()) : ?>
<div id="comments" class="comments">
	<h2 class="comments-title">
		<?php
			printf( _n( 'One thought on &ldquo;%2$s&rdquo;', '%1$s thoughts on &ldquo;%2$s&rdquo;', get_comments_number(), 'terrific' ),
				number_format_i18n( get_comments_number() ), '<span>' . get_the_title() . '</span>' );
		?>
	</h2>
	
	<!-- Comment navigation -->
	<?php if ( get_comment_pages_count() > 1 && get_option('page_comments')) : // are there comments to navigate through ?>
	<nav id="comment-nav-above">
		<h1 class="assistive-text"><?php _e('Comment navigation', 'terrific'); ?></h1>
		<div class="nav-previous"><?php previous_comments_link( __('&larr; Older Comments', 'terrific')); ?></div>
		<div class="nav-next"><?php next_comments_link( __('Newer Comments &rarr;', 'terrific')); ?></div>
	</nav>
	<?php endif; ?>
	
	<!-- List comments -->
	<ol class="commentlist">
		<?php wp_list_comments(array('callback' => 'terrific_comment' )); ?>
	</ol>
	
	<!-- Comment navigation -->
	<?php if ( get_comment_pages_count() > 1 && get_option( 'page_comments' ) ) : // are there comments to navigate through ?>
	<nav id="comment-nav-below">
		<h1 class="assistive-text"><?php _e( 'Comment navigation', 'terrific' ); ?></h1>
		<div class="nav-previous"><?php previous_comments_link( __( '&larr; Older Comments', 'terrific' ) ); ?></div>
		<div class="nav-next"><?php next_comments_link( __( 'Newer Comments &rarr;', 'terrific' ) ); ?></div>
	</nav>
	<?php endif; ?>
	
	<?php if (!comments_open() && !is_page() && post_type_supports(get_post_type(), 'comments')) : ?>
	<p class="nocomments"><?php _e( 'Comments are closed.', 'terrific' ); ?></p>
	<?php endif ?>
	
</div>
<?php endif; ?>
<?php terrific_module('CommentForm', array('post_id' => get_the_id())) ?>
