<h3 class="base"><?php echo $data['title'] ?> (<a class="feed" href="<?= $feed ?>">Feed</a>)</h3>
<ul class="base">
<?php  while ($data['r']->have_posts()) : $data['r']->the_post(); ?>
	<li><a href="<?php the_permalink() ?>" title="<?php echo esc_attr(get_the_title() ? get_the_title() : get_the_ID()); ?>"><?php if ( get_the_title() ) the_title(); else the_ID(); ?></a></li>
<?php endwhile; ?>
</ul>