<?php
global $wp_query;
if ( $wp_query->max_num_pages > 1 ) : ?>
<nav id="<?php echo $data['nav_id']; ?>">
 <h3 class="assistive-text"><?php _e( 'Post navigation', 'terrific' ); ?></h3>
 <div class="nav-previous"><?php next_posts_link( __( '<span class="meta-nav">&larr;</span> Older posts', 'terrific' ) ); ?></div>
 <div class="nav-next"><?php previous_posts_link( __( 'Newer posts <span class="meta-nav">&rarr;</span>', 'terrific' ) ); ?></div>
</nav><!-- #nav-above -->
<?php endif; ?>